const axios = require("axios");
require("dotenv").config();

const feedNews = async (req, res) => {
    console.log(process.env.NEWS_API_KEY)
  try {
    const response = await axios.get("https://newsdata.io/api/1/latest", {
      params: {
        apikey: process.env.NEWS_API_KEY, // ✅ correct param name
        q: "agriculture"
      }
    });


    console.log(response.data)
  } catch (error) {
    console.error("Error fetching news:", error.message);
  }
};

feedNews()
// pub_4eac138e617f4b4e8ce5b61afda56007
// {
//   status: 'success',
//   totalResults: 5728,
//   results: [
//     {
//       article_id: 'd60c025858b51d0be9b77383cc517117',
//       title: 'Une autre crème glacée à la pistache pourrait avoir été contaminée par la salmonelle',
//       link: 'https://www.lapresse.ca/actualites/2025-09-09/une-autre-creme-glacee-a-la-pistache-pourrait-avoir-ete-contaminee-par-la-salmonelle.php',
//       keywords: null,
//       creator: [Array],
//       description: 'Des pistaches, utilisées dans la préparation de crèmes glacées préparées et vendues par l’entreprise Sweemory inc., ont pu être contaminées par la bactérie Salmonella.',
//       content: 'ONLY AVAILABLE IN PAID PLANS',
//       pubDate: '2025-09-10 01:37:26',
//       pubDateTZ: 'UTC',
//       image_url: 'https://mobile-img.lpcdn.ca/v2/924x/r3996/f088e5706b443ade94f0c6a208e1277e.jpg',
//       video_url: null,
//       source_id: 'lapresse_ca',
//       source_name: 'Lapresse Ca',
//       source_priority: 87173,
//       source_url: 'https://www.lapresse.ca',
//       source_icon: 'https://n.bytvi.com/lapresse_ca.png',
//       language: 'french',
//       country: [Array],
//       category: [Array],
//       sentiment: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
//       sentiment_stats: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
//       ai_tag: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
//       ai_region: 'ONLY AVAILABLE IN CORPORATE PLANS',
//       ai_org: 'ONLY AVAILABLE IN CORPORATE PLANS',
//       ai_summary: 'ONLY AVAILABLE IN PAID PLANS',
//       ai_content: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
//       duplicate: false
//     },
//     {
//       article_id: '645ba44331b6324bf048ea7fc54030dd',
//       title: 'UP में इन लोगों को नहीं मिलेगा कृषि जमीन का पट्टा, नियमों में बदलाव की तैयारी',
//       link: 'https://hindi.news18.com/news/uttar-pradesh/lucknow-yogi-government-all-set-to-change-land-allotment-rule-now-no-agriculture-land-patta-for-one-acre-ws-kl-9603749.html',
//       keywords: [Array],
//       creator: [Array],
//       description: 'UP News: उत्तर प्रदेश सरकार ने कृषि भूमि पट्टे के नियमों में बदलाव किया है. अब जिनके पास पहले से एक एकड़ या उससे अधिक जमीन है, उन्हें पट्टा नहीं मिलेगा. यह कदम सीमित भूमि संसाधनों के बेहतर प्रबंधन और भूमिहीन किसानों को प्राथमिकता देने के लिए उठाया गया है.',
//       content: 'ONLY AVAILABLE IN PAID PLANS',
//       pubDate: '2025-09-10 01:36:09',
//       pubDateTZ: 'UTC',
//       image_url: 'https://images.news18.com/ibnkhabar/uploads/2025/08/4956lqqg_yogi-_625x300_26_March_25-2025-08-04d8d947c2795a26b9e320e2a5b5d467-3x2.jpg',
//       video_url: null,
//       source_id: 'hindinews18',
//       source_name: 'News 18 Hindi',
//       source_priority: 4077,
//       source_url: 'https://hindi.news18.com',
//       source_icon: 'https://n.bytvi.com/hindinews18.png',
//       language: 'hindi',
//       country: [Array],
//       category: [Array],
//       sentiment: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
//       sentiment_stats: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
//       ai_tag: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
//       ai_region: 'ONLY AVAILABLE IN CORPORATE PLANS',
//       ai_org: 'ONLY AVAILABLE IN CORPORATE PLANS',
//       ai_summary: 'ONLY AVAILABLE IN PAID PLANS',
//       ai_content: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
//       duplicate: false
//     },
//     {
//       article_id: 'e7139a6c49d96eecda566d41d8b3bb1a',
//       title: '“Estamos preservando o que eles não preservaram”, diz Lula na Amazônia',
//       link: 'https://contilnetnoticias.com.br/2025/09/estamos-preservando-o-que-eles-nao-preservaram-diz-lula-na-amazonia/',
//       keywords: [Array],
//       creator: [Array],
//       description: 'O presidente Luiz Inácio Lula da Silva defendeu, nesta terça-feira (9), as ações de preservação da Amazônia por parte do governo brasileiro. Ele assinou, em cerimônia em Manaus, a implementação...',
//       content: 'ONLY AVAILABLE IN PAID PLANS',
//       pubDate: '2025-09-10 01:36:01',
//       pubDateTZ: 'UTC',
//       image_url: 'https://cdn.jsdelivr.net/gh/sergiosdlima/assets-ebc@1.0.0/abr/assets/images/logo-agenciabrasil.svg',
//       video_url: null,
//       source_id: 'contilnetnoticias',
//       source_name: 'Contilnet Notícias',
//       source_priority: 155904,
//       source_url: 'https://contilnetnoticias.com.br',
//       source_icon: 'https://n.bytvi.com/contilnetnoticias.png',
//       language: 'portuguese',
//       country: [Array],
//       category: [Array],
//       sentiment: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
//       sentiment_stats: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
//       ai_tag: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
//       ai_region: 'ONLY AVAILABLE IN CORPORATE PLANS',
//       ai_org: 'ONLY AVAILABLE IN CORPORATE PLANS',
//       ai_summary: 'ONLY AVAILABLE IN PAID PLANS',
//       ai_content: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
//       duplicate: true
//     },
//     {
//       article_id: 'a3c952b1fed2192f8558063980d5a319',
//       title: 'Solar Energy Giant Sun King Unveils Brand Refresh',
//       link: 'https://www.newsghana.com.gh/solar-energy-giant-sun-king-unveils-brand-refresh/',
//       keywords: [Array],
//       creator: [Array],
//       description: 'News Ghana, Latest Updates and Breaking News of Ghana, Roger A. Agana, https://www.newsghana.com.gh/solar-energy-giant-sun-king-unveils-brand-refresh/Off-grid solar company Sun King has launched a refreshed corporate identity as the firm expands beyond traditional solar home systems into smartphones and commercial energy solutions across Africa and Asia. The Nairobi-based company unveiled its new logo Thursday alongside a marketing campaign targeting households and businesses seeking alternatives to unreliable grid electricity. The rebrand reflects [...] News Ghana, Latest Updates and Breaking News of Ghana, Roger A. Agana, https://www.newsghana.com.gh/solar-energy-giant-sun-king-unveils-brand-refresh/',
//       content: 'ONLY AVAILABLE IN PAID PLANS',
//       pubDate: '2025-09-10 01:34:42',
//       pubDateTZ: 'UTC',
//       image_url: 'https://b843437.smushcdn.com/843437/wp-content/uploads/2025/09/Sun-King-Unveils-Brand-Refresh-696x464.jpg?lossy=2&strip=1&webp=1',
//       video_url: null,
//       source_id: 'newsghana',
//       source_name: 'News Ghana',
//       source_priority: 177556,
//       source_url: 'https://newsghana.com.gh',
//       source_icon: 'https://n.bytvi.com/newsghana.png',
//       language: 'english',
//       country: [Array],
//       category: [Array],
//       sentiment: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
//       sentiment_stats: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
//       ai_tag: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
//       ai_region: 'ONLY AVAILABLE IN CORPORATE PLANS',
//       ai_org: 'ONLY AVAILABLE IN CORPORATE PLANS',
//       ai_summary: 'ONLY AVAILABLE IN PAID PLANS',
//       ai_content: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
//       duplicate: false
//     },
//     {
//       article_id: '1a424638452feb63fdc388e7de71b456',
//       title: 'Inicia campaña de frío en todo el país: Se prevé la siembra de 517 mil hectáreas de cultivos',
//       link: 'http://www.cubadebate.cu/noticias/2025/09/09/inicia-campana-de-frio-en-todo-el-pais-se-preve-la-siembra-de-517-mil-hectareas-de-cultivos/',
//       keywords: [Array],
//       creator: [Array],
//       description: 'El sector agrícola cubano dio inicio a principios de septiembre a la Campaña de Frío 2025-2026, un esfuerzo nacional que tiene como meta la siembra de 517 mil hectáreas de cultivos varios en empresas agropecuarias de todo el país, según informó Yohan García, director general de Agricultura del Ministerio del ramo (MINAG).The post Inicia campaña de frío en todo el país: Se prevé la siembra de 517 mil hectáreas de cultivos first appeared on Cubadebate.',
//       content: 'ONLY AVAILABLE IN PAID PLANS',
//       pubDate: '2025-09-10 01:34:24',
//       pubDateTZ: 'UTC',
//       image_url: 'http://media.cubadebate.cu/wp-content/uploads/2020/06/siembra-boniato-ciego-de-avila.jpg',
//       video_url: null,
//       source_id: 'cubadebate',
//       source_name: 'Cubadebate',
//       source_priority: 36284,
//       source_url: 'http://www.cubadebate.cu',
//       source_icon: 'https://n.bytvi.com/cubadebate.png',
//       language: 'spanish',
//       country: [Array],
//       category: [Array],
//       sentiment: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
//       sentiment_stats: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
//       ai_tag: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
//       ai_region: 'ONLY AVAILABLE IN CORPORATE PLANS',
//       ai_org: 'ONLY AVAILABLE IN CORPORATE PLANS',
//       ai_summary: 'ONLY AVAILABLE IN PAID PLANS',
//       ai_content: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
//       duplicate: false
//     },
//     {
//       article_id: 'ac68799321b5d668cfad4438ad79730a',
//       title: 'खेत के मेड़ों पर लगा दें ये 5 पौधे, 10 साल में बन सकते हैं करोड़पति!',
//       link: 'https://hindi.news18.com/photogallery/agriculture/agriculture-news-hazaribagh-krishi-scientist-dr-arvind-kumar-suggests-5-beneficial-trees-farming-sagwan-chandan-eucalyptus-shirisha-benfits-local18-ws-l-9603585.html',
//       keywords: [Array],
//       creator: [Array],
//       description: 'Agriculture News: हजारीबाग के आईसेक्ट विश्वविद्यालय के कृषि वैज्ञानिक डॉ अरविंद कुमार ने किसानों को सागवान, चंदन, यूकेलिप्टस, पॉपुलर और सफेद सिरस के पेड़ लगाने की सलाह दी है. उन्होंने कहा किसान इससे जबरदस्त कमाई कर सकते हैं.',
//       content: 'ONLY AVAILABLE IN PAID PLANS',
//       pubDate: '2025-09-10 01:33:05',
//       pubDateTZ: 'UTC',
//       image_url: 'https://images.news18.com/ibnkhabar/uploads/2025/09/HYP_5441078_cropped_10092025_003058_20250910_002617_watermark__1-3x2.jpg',
//       video_url: null,
//       source_id: 'hindinews18',
//       source_name: 'News 18 Hindi',
//       source_priority: 4077,
//       source_url: 'https://hindi.news18.com',
//       source_icon: 'https://n.bytvi.com/hindinews18.png',
//       language: 'hindi',
//       country: [Array],
//       category: [Array],
//       sentiment: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
//       sentiment_stats: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
//       ai_tag: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
//       ai_region: 'ONLY AVAILABLE IN CORPORATE PLANS',
//       ai_org: 'ONLY AVAILABLE IN CORPORATE PLANS',
//       ai_summary: 'ONLY AVAILABLE IN PAID PLANS',
//       ai_content: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
//       duplicate: false
//     },
//     {
//       article_id: '2a458d3a9a322124e084281baa47b7a4',
//       title: 'Exploring Stirring And Dispersing Kettle Markets: Market Strategies, Insights, and Share Forecast for 2025-2031',
//       link: 'https://www.openpr.com/news/4176441/exploring-stirring-and-dispersing-kettle-markets-market',
//       keywords: [Array],
//       creator: [Array],
//       description: 'The global market for Stirring And Dispersing Kettle was estimated to be worth US$ million in 2024 and is forecast to a readjusted size of US$ million by 2031 with a CAGR of %during the forecast period 2025-2031.Global Leading Market',
//       content: 'ONLY AVAILABLE IN PAID PLANS',
//       pubDate: '2025-09-10 01:32:24',
//       pubDateTZ: 'UTC',
//       image_url: 'https://cdn.open-pr.com/L/9/L910214174_g.jpg',
//       video_url: null,
//       source_id: 'openpr',
//       source_name: 'Openpr.com',
//       source_priority: 31972,
//       source_url: 'https://www.openpr.com',
//       source_icon: 'https://n.bytvi.com/openpr.png',
//       language: 'english',
//       country: [Array],
//       category: [Array],
//       sentiment: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
//       sentiment_stats: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
//       ai_tag: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
//       ai_region: 'ONLY AVAILABLE IN CORPORATE PLANS',
//       ai_org: 'ONLY AVAILABLE IN CORPORATE PLANS',
//       ai_summary: 'ONLY AVAILABLE IN PAID PLANS',
//       ai_content: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
//       duplicate: false
//     },
//     {
//       article_id: 'fb26c0ea39216054580fa099001c1c1e',
//       title: 'Not zero, yes energy',
//       link: 'https://www.spectator.com.au/2025/09/not-zero-yes-energy/',
//       keywords: [Array],
//       creator: [Array],
//       description: 'Reality will eventually yank Labor off the destructive path towards its Net Zero nirvana. This has been said, written, broadcast,...What to read next: Will PNG’s energy crisis cost Australian taxpayers? | Chris Bowen’s socialist, energy-poor future | The most important sentence about Net Zero published this year | Law and the Leviathan: human rights courts and democracy',
//       content: 'ONLY AVAILABLE IN PAID PLANS',
//       pubDate: '2025-09-10 01:32:15',
//       pubDateTZ: 'UTC',
//       image_url: 'https://www.spectator.com.au/wp-content/uploads/2017/11/GettyImages-109832459.jpg',
//       video_url: null,
//       source_id: 'spectator_au',
//       source_name: 'The Spectator Australia',
//       source_priority: 310699,
//       source_url: 'https://www.spectator.com.au',
//       source_icon: 'https://n.bytvi.com/spectator_au.png',
//       language: 'english',
//       country: [Array],
//       category: [Array],
//       sentiment: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
//       sentiment_stats: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
//       ai_tag: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
//       ai_region: 'ONLY AVAILABLE IN CORPORATE PLANS',
//       ai_org: 'ONLY AVAILABLE IN CORPORATE PLANS',
//       ai_summary: 'ONLY AVAILABLE IN PAID PLANS',
//       ai_content: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
//       duplicate: false
//     },
//     {
//       article_id: '6da501bc61d2ff20265b41715f0c545c',
//       title: 'The rise of hydrogen-fuelled tractors and vehicles',
//       link: 'https://hydrogen-central.com/the-rise-of-hydrogen-fuelled-tractors-and-vehicles/',
//       keywords: [Array],
//       creator: [Array],
//       description: 'The rise of hydrogen-fuelled tractors and vehicles Hydrogen could offer Irish farmers a way to reduce carbon emissions, avoid fossil fuel price volatility and make better use of Ireland’s rich [...]The post The rise of hydrogen-fuelled tractors and vehicles appeared first on Hydrogen Central.',
//       content: 'ONLY AVAILABLE IN PAID PLANS',
//       pubDate: '2025-09-10 01:32:03',
//       pubDateTZ: 'UTC',
//       image_url: 'https://hydrogen-central.com/wp-content/uploads/2025/09/hydrogen-fuelled-tractors-vehicles.png',
//       video_url: null,
//       source_id: 'hydrogencentral',
//       source_name: 'Hydrogen Central',
//       source_priority: 695770,
//       source_url: 'https://hydrogen-central.com',
//       source_icon: 'https://n.bytvi.com/hydrogencentral.jpg',
//       language: 'english',
//       country: [Array],
//       category: [Array],
//       sentiment: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
//       sentiment_stats: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
//       ai_tag: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
//       ai_region: 'ONLY AVAILABLE IN CORPORATE PLANS',
//       ai_org: 'ONLY AVAILABLE IN CORPORATE PLANS',
//       ai_summary: 'ONLY AVAILABLE IN PAID PLANS',
//       ai_content: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
//       duplicate: false
//     },
//     {
//       article_id: '57871b543570b04b833a1403d6247975',
//       title: '‘Stand firmly with flood-hit states’: PM declares Rs 1,600 cr aid for Punjab, Rs 1,500 cr for HP',
//       link: 'https://indianexpress.com/article/political-pulse/stand-firmly-with-flood-hit-states-pm-declares-rs-1600-cr-aid-for-punjab-rs-1500-cr-for-hp-10240213/',
//       keywords: [Array],
//       creator: [Array],
//       description: 'Modi conducts aerial surveys of flood-affected belts in Himachal Pradesh, Punjab; meets victims; holds meetings to take stock of relief, damage',
//       content: 'ONLY AVAILABLE IN PAID PLANS',
//       pubDate: '2025-09-10 01:30:50',
//       pubDateTZ: 'UTC',
//       image_url: 'https://images.indianexpress.com/2025/09/09093-20250909376l.jpg',
//       video_url: null,
//       source_id: 'indianexpress',
//       source_name: 'The Indian Express',
//       source_priority: 1386,
//       source_url: 'https://indianexpress.com',
//       source_icon: 'https://n.bytvi.com/indianexpress.png',
//       language: 'english',
//       country: [Array],
//       category: [Array],
//       sentiment: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
//       sentiment_stats: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
//       ai_tag: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
//       ai_region: 'ONLY AVAILABLE IN CORPORATE PLANS',
//       ai_org: 'ONLY AVAILABLE IN CORPORATE PLANS',
//       ai_summary: 'ONLY AVAILABLE IN PAID PLANS',
//       ai_content: 'ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS',
//       duplicate: false
//     }
//   ],
//   nextPage: '1757467850940267045'
// }
// akshay~$